apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: docling-extractor
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/docling-extractor:latest
          ports:
            - containerPort: 8080
          env:
            - name: UVICORN_HOST
              value: "0.0.0.0"
            - name: UVICORN_PORT
              value: "8080"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
